@startuml 演習6-3_ユースケース図
left to right direction
actor 利用者
actor 看護師

rectangle 診察予約システム{
    usecase メニュー
    usecase 予約と確認
    usecase あなたの順番
    usecase 今の順番
}
利用者 --> メニュー
利用者 --> 予約と確認
利用者 --> あなたの順番
利用者 --> 今の順番
今の順番 <-- 看護師

@enduml