@startuml 診察
[*] -right-> メニュー : 接続
メニュー -right-> [*] : 切断
メニュー --> 情報入力 : 予約と確認
メニュー <-right- 情報入力 : 取り消し\nボタンを押す
メニュー <-- あなたの順番 : メニューへ
メニュー --> 今の順番 : 患者の順番を\n表示
メニュー <-right- 今の順番 : 患者番号を\n一つ増やす
情報入力 -right-> あなたの順番 : 登録ボタンを押す
情報入力 -right-> あなたの順番 : 確認ボタンを押す
@enduml